using System.Collections.Concurrent;
using System.Runtime.InteropServices;
using VExplorer.Core.FileSystem;

namespace VExplorer.Shell.FileSystem;

/// <summary>
/// Implements <see cref="IShellInfoProvider"/> with <c>SHGetFileInfo</c>.
/// <para>
/// P/Invoke is hand-written rather than generated by CsWin32: CsWin32 refuses to
/// emit <c>SHGetFileInfo</c> for an AnyCPU target (PInvoke005). The friendly type
/// name and a stable system-image-list index are resolved together; the icon
/// bitmap itself is materialized on demand through <see cref="CopyIcon"/>.
/// </para>
/// <para>
/// Ordinary files and folders are resolved with <c>SHGFI_USEFILEATTRIBUTES</c>
/// (no disk I/O, never blocks on slow/network paths) and cached by extension.
/// Entries whose icon is per-instance — executables, shortcuts, drive roots —
/// are resolved from the real path and not cached.
/// </para>
/// </summary>
public sealed class WindowsShellInfoProvider : IShellInfoProvider
{
    private const uint SHGFI_ICON = 0x000000100;
    private const uint SHGFI_USEFILEATTRIBUTES = 0x000000010;
    private const uint SHGFI_TYPENAME = 0x000000400;
    private const uint SHGFI_SYSICONINDEX = 0x000004000;
    private const uint SHGFI_SMALLICON = 0x000000001;
    private const uint SHGFI_PIDL = 0x000000008;

    private const uint FILE_ATTRIBUTE_NORMAL = 0x00000080;
    private const uint FILE_ATTRIBUTE_DIRECTORY = 0x00000010;

    // Cache key for the single generic-folder entry.
    private const string FolderKey = "<dir>";

    // Cache key for files with no extension.
    private const string NoExtKey = "<noext>";

    // Type name + icon index keyed by extension (or the sentinels above).
    private readonly ConcurrentDictionary<string, ShellItemInfo> _cache = new(
        StringComparer.OrdinalIgnoreCase
    );

    public ShellItemInfo Resolve(string fullPath, string extension, bool isDirectory)
    {
        if (isDirectory)
        {
            return IsDriveRoot(fullPath)
                ? Query(fullPath, FILE_ATTRIBUTE_DIRECTORY, useAttributes: false)
                : _cache.GetOrAdd(
                    FolderKey,
                    _ => Query("dir", FILE_ATTRIBUTE_DIRECTORY, useAttributes: true)
                );
        }

        if (IsPerInstance(extension))
        {
            return Query(fullPath, FILE_ATTRIBUTE_NORMAL, useAttributes: false);
        }

        string ext = extension.ToLowerInvariant();
        string key = ext.Length == 0 ? NoExtKey : ext;
        return _cache.GetOrAdd(
            key,
            _ => Query("x" + ext, FILE_ATTRIBUTE_NORMAL, useAttributes: true)
        );
    }

    public ShellItemInfo Resolve(Location location, string extension, bool isDirectory)
    {
        if (location.TryGetFileSystemPath(out string path) && path.Length > 0)
        {
            return Resolve(path, extension, isDirectory);
        }
        // Shell-namespace location: resolve via its PIDL.
        nint pidl = CreatePidl(location);
        if (pidl == 0)
        {
            return new ShellItemInfo("", 0);
        }
        try
        {
            SHFILEINFO info = default;
            nint result = SHGetFileInfoPidl(
                pidl,
                0,
                ref info,
                (uint)Marshal.SizeOf<SHFILEINFO>(),
                SHGFI_PIDL | SHGFI_TYPENAME | SHGFI_SYSICONINDEX | SHGFI_SMALLICON
            );
            string typeName = result == 0 ? "" : info.szTypeName;
            return new ShellItemInfo(typeName, info.iIcon);
        }
        finally
        {
            CoTaskMemFree(pidl);
        }
    }

    public nint CopyIcon(Location location, string extension, bool isDirectory)
    {
        if (location.TryGetFileSystemPath(out string path) && path.Length > 0)
        {
            return CopyIcon(path, extension, isDirectory);
        }
        nint pidl = CreatePidl(location);
        if (pidl == 0)
        {
            return 0;
        }
        try
        {
            SHFILEINFO info = default;
            SHGetFileInfoPidl(
                pidl,
                0,
                ref info,
                (uint)Marshal.SizeOf<SHFILEINFO>(),
                SHGFI_PIDL | SHGFI_ICON | SHGFI_SMALLICON
            );
            return info.hIcon;
        }
        finally
        {
            CoTaskMemFree(pidl);
        }
    }

    /// <summary>
    /// Builds an absolute PIDL for a shell-namespace location: from its
    /// <c>KNOWNFOLDERID</c> when set, else by parsing its parsing name. The caller
    /// frees the result with <see cref="CoTaskMemFree"/>. Returns 0 on failure.
    /// </summary>
    private static nint CreatePidl(Location location)
    {
        if (location.KnownFolderId != Guid.Empty)
        {
            Guid id = location.KnownFolderId;
            if (SHGetKnownFolderIDList(in id, 0, 0, out nint pidl) == 0)
            {
                return pidl;
            }
        }
        if (SHParseDisplayName(location.ParsingName, 0, out nint parsed, 0, out _) == 0)
        {
            return parsed;
        }
        return 0;
    }

    public nint CopyIcon(string fullPath, string extension, bool isDirectory)
    {
        bool perInstance = isDirectory ? IsDriveRoot(fullPath) : IsPerInstance(extension);
        uint attrs = isDirectory ? FILE_ATTRIBUTE_DIRECTORY : FILE_ATTRIBUTE_NORMAL;

        // For cacheable (attribute-based) entries a dummy path is sufficient;
        // per-instance entries need the real path so the embedded icon is read.
        string path =
            perInstance ? fullPath
            : isDirectory ? "dir"
            : "x" + extension.ToLowerInvariant();

        uint flags = SHGFI_ICON | SHGFI_SMALLICON;
        if (!perInstance)
        {
            flags |= SHGFI_USEFILEATTRIBUTES;
        }

        SHFILEINFO info = default;
        SHGetFileInfo(path, attrs, ref info, (uint)Marshal.SizeOf<SHFILEINFO>(), flags);
        return info.hIcon;
    }

    public void DestroyIcon(nint hIcon)
    {
        if (hIcon != 0)
        {
            DestroyIconNative(hIcon);
        }
    }

    /// <summary>Resolves type name + system icon index without creating an icon.</summary>
    private static ShellItemInfo Query(string path, uint attributes, bool useAttributes)
    {
        uint flags = SHGFI_TYPENAME | SHGFI_SYSICONINDEX | SHGFI_SMALLICON;
        if (useAttributes)
        {
            flags |= SHGFI_USEFILEATTRIBUTES;
        }

        SHFILEINFO info = default;
        nint result = SHGetFileInfo(
            path,
            attributes,
            ref info,
            (uint)Marshal.SizeOf<SHFILEINFO>(),
            flags
        );

        // On failure SHGetFileInfo returns 0; leave TypeName empty so the caller
        // falls back to its own label.
        string typeName = result == 0 ? "" : info.szTypeName;
        return new ShellItemInfo(typeName, info.iIcon);
    }

    private static bool IsDriveRoot(string fullPath)
    {
        string? root = Path.GetPathRoot(fullPath);
        return root != null
            && string.Equals(
                root.TrimEnd('\\'),
                fullPath.TrimEnd('\\'),
                StringComparison.OrdinalIgnoreCase
            );
    }

    private static bool IsPerInstance(string extension)
    {
        return extension.ToLowerInvariant() is ".exe" or ".lnk" or ".ico" or ".url";
    }

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    private struct SHFILEINFO
    {
        public nint hIcon;
        public int iIcon;
        public uint dwAttributes;

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 260)]
        public string szDisplayName;

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 80)]
        public string szTypeName;
    }

    [DllImport("shell32.dll", CharSet = CharSet.Unicode, EntryPoint = "SHGetFileInfoW")]
    private static extern nint SHGetFileInfo(
        string pszPath,
        uint dwFileAttributes,
        ref SHFILEINFO psfi,
        uint cbFileInfo,
        uint uFlags
    );

    [DllImport("user32.dll", EntryPoint = "DestroyIcon", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static extern bool DestroyIconNative(nint hIcon);

    // PIDL-based shell icon resolution for shell-namespace items. Hand-written for
    // the same reason as SHGetFileInfo above (CsWin32 won't emit it for AnyCPU).
    [DllImport("shell32.dll", EntryPoint = "SHGetFileInfoW")]
    private static extern nint SHGetFileInfoPidl(
        nint pidl,
        uint dwFileAttributes,
        ref SHFILEINFO psfi,
        uint cbFileInfo,
        uint uFlags
    );

    [DllImport("shell32.dll")]
    private static extern int SHGetKnownFolderIDList(
        in Guid rfid,
        uint dwFlags,
        nint hToken,
        out nint ppidl
    );

    [DllImport("shell32.dll", CharSet = CharSet.Unicode)]
    private static extern int SHParseDisplayName(
        string pszName,
        nint pbc,
        out nint ppidl,
        uint sfgaoIn,
        out uint psfgaoOut
    );

    [DllImport("ole32.dll")]
    private static extern void CoTaskMemFree(nint pv);
}
